# Generated by Django 4.0.4 on 2022-05-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('google_place_id', models.CharField(blank=True, max_length=512)),
                ('google_rating', models.FloatField()),
                ('google_icon', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MenuEntryAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(choices=[('CEREALS', 'cereals'), ('CRUSTACEANS', 'crustaceans'), ('EGGS', 'eggs'), ('FISH', 'fish'), ('PEANUTS', 'peanuts'), ('SOYBEANS', 'soybeans'), ('MILK', 'milk'), ('NUTS', 'nuts'), ('CELERY', 'celery'), ('MUSTARD', 'mustard'), ('SESAME_SEEDS', 'sesame_seeds'), ('SULPHUR_DIOXIDE', 'sulphur_dioxide'), ('LUPIN', 'lupin'), ('MOLLUSCS', 'molluscs')], max_length=128)),
                ('menu_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='restaurants.menuentry')),
            ],
        ),
        migrations.AddField(
            model_name='menuentry',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_entries', to='restaurants.restaurant'),
        ),
        migrations.CreateModel(
            name='GooglePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('photo_reference', models.CharField(max_length=1024)),
                ('index', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_photos', to='restaurants.restaurant')),
            ],
        ),
    ]
