# Generated by Django 4.0.4 on 2022-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentryallergen',
            name='allergen',
            field=models.CharField(choices=[('CEREALS', 'Cereals'), ('CRUSTACEANS', 'Crustaceans'), ('EGGS', 'Eggs'), ('FISH', 'Fish'), ('PEANUTS', 'Peanuts'), ('SOYBEANS', 'Soybeans'), ('MILK', 'Milk'), ('NUTS', 'Nuts'), ('CELERY', 'Celery'), ('MUSTARD', 'Mustard'), ('SESAME_SEEDS', 'Sesame seeds'), ('SULPHUR_DIOXIDE', 'Sulphur dioxide'), ('LUPIN', 'Lupin'), ('MOLLUSCS', 'Molluscs')], max_length=128),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='google_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
