# Generated by Django 4.0.4 on 2022-05-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuentryallergen_allergen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='google_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='google_icon',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='google_place_id',
        ),
        migrations.AddField(
            model_name='menuentry',
            name='photo_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.DeleteModel(
            name='GooglePhoto',
        ),
    ]
