# Generated by Django 4.0.4 on 2022-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_google_rating_restaurant_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address_country',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_locality',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_address',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
