# Generated by Django 4.0.4 on 2022-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
