# Generated by Django 4.0.4 on 2022-05-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_menuentry_index_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuentryallergen',
            unique_together={('menu_entry', 'allergen')},
        ),
    ]
